name: Generate Pac-Man Game

on:
  schedule:
    - cron: '0 0 * * *'      # roda 1 vez por dia à 00:00 UTC
  workflow_dispatch:          # botão “Run workflow”
  push:
    branches: [main]          # dispara a cada push na main

permissions:
  contents: write             # permite dar push na branch 'output'

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4   # garante cópia do repo

      - name: Generate SVGs
        uses: abozanona/pacman-contribution-graph@v1
        with:
          github_user_name: ${{ github.repository_owner }}

      - name: Publish on branch 'output'
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
